#!/bin/bash
echo /home/reverie/anaconda3/bin:/home/reverie/anaconda3/condabin:/home/reverie/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin | tr -s ':' '\n' | wc -l
